# Setup
title:        Alfred Jiang
tagline:      欢迎访问 Alfred Jiang 的个人主页
baseurl:      "viktyz.github.io"
paginate:     1

# About/contact
author:
  name:       viktyz
  url:        viktyz.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

include: ["_others","js"]
